# Generated by Django 5.2.3 on 2025-07-09 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=70)),
                ('salary', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pasword', models.CharField(max_length=8)),
                ('con_password', models.CharField(max_length=8)),
            ],
        ),
    ]
